export enum JobSource {
  GREENHOUSE = 'GREENHOUSE',
  LEVER = 'LEVER',
  ASHBY = 'ASHBY',
  TEAMTAILOR = 'TEAMTAILOR',
  PERSONIO = 'PERSONIO',
  WORKABLE = 'WORKABLE',
  SMARTRECRUITERS = 'SMARTRECRUITERS',
  WORKDAY = 'WORKDAY',
  ICIMS = 'ICIMS',
  TALEO = 'TALEO',
  SUCCESSFACTORS = 'SUCCESSFACTORS',

  LINKEDIN = 'LINKEDIN',
  INDEED = 'INDEED',
  GLASSDOOR = 'GLASSDOOR',
  WELLFOUND = 'WELLFOUND',
  DICE = 'DICE',
  SEEK = 'SEEK',
  REED = 'REED',
  EURES = 'EURES',

  GOOGLE_JOBS = 'GOOGLE_JOBS',
  COMPANY_CAREER = 'COMPANY_CAREER',

  RSS = 'RSS',
  API = 'API',
  MANUAL = 'MANUAL',
}
export enum JobType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  INTERNSHIP = 'INTERNSHIP',
  TEMPORARY = 'TEMPORARY',
  FREELANCE = 'FREELANCE',
}

export enum WorkMode {
  REMOTE = 'REMOTE',
  ONSITE = 'ONSITE',
  HYBRID = 'HYBRID',
}

export enum VisaSponsorshipStatus {
  UNKNOWN = 'UNKNOWN',

  // Sponsorship
  SPONSORS = 'SPONSORS',
  DOES_NOT_SPONSOR = 'DOES_NOT_SPONSOR',
  CASE_BY_CASE = 'CASE_BY_CASE',
  SPONSORS_SPECIFIC_ROLES = 'SPONSORS_SPECIFIC_ROLES',
  SPONSORS_SPECIFIC_COUNTRIES = 'SPONSORS_SPECIFIC_COUNTRIES',
  SPONSORS_SENIOR_ROLES = 'SPONSORS_SENIOR_ROLES',

  // Immigration / Work Permit Support
  IMMIGRATION_SUPPORT = 'IMMIGRATION_SUPPORT',
  WORK_PERMIT_SUPPORT = 'WORK_PERMIT_SUPPORT',
  VISA_APPLICATION_SUPPORT = 'VISA_APPLICATION_SUPPORT',
  VISA_PROCESSING_SUPPORT = 'VISA_PROCESSING_SUPPORT',
  IMMIGRATION_LAWYER_SUPPORT = 'IMMIGRATION_LAWYER_SUPPORT',

  // Relocation
  RELOCATION_SUPPORT = 'RELOCATION_SUPPORT',
  RELOCATION_PACKAGE = 'RELOCATION_PACKAGE',
  RELOCATION_ASSISTANCE = 'RELOCATION_ASSISTANCE',
  RELOCATION_FLIGHT_SUPPORT = 'RELOCATION_FLIGHT_SUPPORT',
  TEMPORARY_HOUSING_SUPPORT = 'TEMPORARY_HOUSING_SUPPORT',

  // Conditional situations
  SPONSORS_AFTER_PROBATION = 'SPONSORS_AFTER_PROBATION',
  SPONSORS_AFTER_JOINING = 'SPONSORS_AFTER_JOINING',
  SPONSORSHIP_NEGOTIABLE = 'SPONSORSHIP_NEGOTIABLE',
  SPONSORSHIP_DEPENDS_ON_CANDIDATE = 'SPONSORSHIP_DEPENDS_ON_CANDIDATE',
  SPONSORSHIP_DEPENDS_ON_ROLE = 'SPONSORSHIP_DEPENDS_ON_ROLE',

  // Existing work authorization required
  EXISTING_WORK_AUTHORIZATION_REQUIRED = 'EXISTING_WORK_AUTHORIZATION_REQUIRED',
  LOCAL_WORK_AUTHORIZATION_REQUIRED = 'LOCAL_WORK_AUTHORIZATION_REQUIRED',
  NO_VISA_NEEDED = 'NO_VISA_NEEDED',

  // Job-posting signals
  VISA_SPONSORSHIP_MENTIONED = 'VISA_SPONSORSHIP_MENTIONED',
  VISA_SPONSORSHIP_NOT_MENTIONED = 'VISA_SPONSORSHIP_NOT_MENTIONED',
  VISA_SPONSORSHIP_RESTRICTED = 'VISA_SPONSORSHIP_RESTRICTED',

  // Company / recruiter verification
  SPONSORSHIP_VERIFIED = 'SPONSORSHIP_VERIFIED',
  SPONSORSHIP_UNVERIFIED = 'SPONSORSHIP_UNVERIFIED',
  RECRUITER_CONFIRMED = 'RECRUITER_CONFIRMED',

  // Historical / uncertain
  PREVIOUSLY_SPONSORED = 'PREVIOUSLY_SPONSORED',
  SPONSORSHIP_STATUS_OUTDATED = 'SPONSORSHIP_STATUS_OUTDATED',
}

export enum ApplicationStatus {
  SAVED = 'SAVED',
  APPLYING = 'APPLYING',
  APPLIED = 'APPLIED',
  SCREENING = 'SCREENING',
  INTERVIEWING = 'INTERVIEWING',
  OFFERED = 'OFFERED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum ResumeStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum NotificationType {
  JOB_MATCH = 'JOB_MATCH',
  APPLICATION_UPDATE = 'APPLICATION_UPDATE',
  INTERVIEW_REMINDER = 'INTERVIEW_REMINDER',
  VISA_ALERT = 'VISA_ALERT',
  RESUME_TIP = 'RESUME_TIP',
  GENERAL = 'GENERAL',
}

export enum NotificationChannel {
  EMAIL = 'EMAIL',
  PUSH = 'PUSH',
  IN_APP = 'IN_APP',
}

export enum UserRole {
  USER = 'USER',
  PREMIUM = 'PREMIUM',
  ADMIN = 'ADMIN',
}

export enum ATSProvider {
  GREENHOUSE = 'GREENHOUSE',
  LEVER = 'LEVER',
  WORKDAY = 'WORKDAY',
  SUCCESSFACTORS = 'SUCCESSFACTORS',
  TALEO = 'TALEO',
  ICIMS = 'ICIMS',
  SMART_RECRUITERS = 'SMART_RECRUITERS',
  GENERIC = 'GENERIC',
}

export enum AIServiceType {
  RESUME_MATCH = 'RESUME_MATCH',
  VISA_DETECTION = 'VISA_DETECTION',
  COVER_LETTER = 'COVER_LETTER',
  INTERVIEW_PREP = 'INTERVIEW_PREP',
  RESUME_IMPROVEMENT = 'RESUME_IMPROVEMENT',
  JOB_ANALYSIS = 'JOB_ANALYSIS',
}

export enum AgentType {
  COORDINATOR = 'COORDINATOR',
  SEARCH = 'SEARCH',
  VISA_DETECTION = 'VISA_DETECTION',
  RESUME_MATCH = 'RESUME_MATCH',
  RESUME_IMPROVEMENT = 'RESUME_IMPROVEMENT',
  COVER_LETTER = 'COVER_LETTER',
  INTERVIEW = 'INTERVIEW',
  LEARNING = 'LEARNING',
}

export enum EmbeddingModel {
  NOMIC_EMBED_TEXT = 'nomic-embed-text',
  LLAMA3 = 'llama3',
  MISTRAL = 'mistral',
}

export enum CrawlerStatus {
  IDLE = 'IDLE',
  RUNNING = 'RUNNING',
  PAUSED = 'PAUSED',
  ERROR = 'ERROR',
  COMPLETED = 'COMPLETED',
}

